Add types to toArray
Microsoft/HVMobile_VNext pull request #117
Opened 2017-07-13 18:59 UTC by miburf

Allows Swift things like:

readOnlyThings = things.toArray().filter
        {
            $0.isReadOnly
        }

I haven't seen a way to do it without the toArray() that isn't totally rewriting the Collection classes

2017-07-13 18:59 UTC, msftclas commented
@miburf,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-07-13 22:33 UTC, namalu requested changes
We shouldn't be doing this. We need to fix the root cause of the issue. We can't ask consumers of the public SDK to use the toArray on every collection. Collections need to work in both Objective-C and Swift.

2017-07-14 18:11 UTC, miburf commented
NSArrays are specially bridged to Swift arrays.  There’s no enumeration or other method to implement to get it to work easily.  We're already doing the NSFastEnumeration.

1. We can change MHVCollection to be a subclass of NSMutableArray (which Apple doesn’t recommend). That causes the object type to be lost in a lot of cases in Swift, so doesn't work either. 
Adding the type to a few methods for every collection (so MHVStringCollection adds - (NSString *)objectAtIndex:(NSUInteger)index; and others) works for some methods from Swift, but not all. 
I still haven’t found any way to get the types right so collection.forEach(…) gets the object type if it's an NSArray subclass.

2. Convert every collection to a typed array, MHVThingCollection —> NSArray<MHVThing*>  
That would bridge to swift the best and be future-proof for anything that changes between objective-C and Swift.  That will take some work to move all the current MHVCollection methods to categories, and do the correct serialization.

3. Leave as in this code review, requiring .toArray() from swift.


#2 is a lot of work, but seems like the best solution so that HealthVault is the most useable from Swift.

2017-07-18 17:47 UTC, namalu requested changes

2017-07-18 17:47 UTC, namalu commented on Example/Tests/Caching/MHVThingCacheSyncTests.m
> +    testPerson.records = @[];
It looks like you can just delete this line - the testPerson.records gets set 4 lines later.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Headers/MHVCommon.h
> +#import "NSArray+MHVThing.h"
We need to eventually get rid of this file, so we should not add anymore imports. I've seen this imported in a quite few places and it's not a good practice. Ideally, classes should just import what they need.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Models/Categories/NSArray+Utils.h
> +- (NSArray *)arrayByRemovingObjectAtIndex:(NSUInteger)index;
Let's not add this to the extensions - It is used in one place. The practice of making a mutable array should be done where needed.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/ThingTypes/MHVCollection.h
> +@interface MHVCollectionInternal<__covariant ObjectType> : NSMutableArray
This file should be deleted at the end of this exercise. This was the root of all of our issues, and there should be no reason to keep this around.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Types/MHVThing.m
> +//static NSString *const c_element_thing = @"thing";
It looks like all of this code can be deleted?

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Types/MHVThingFilter.h
> +@property (readwrite, nonatomic, strong)  NSArray<NSString *> *typeIDs;
I'm a little concerned that this changed to readwrite when readonly was fine for this collection before.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Types/MHVThingFilter.h
> +@interface MHVThingFilterCollectionInternal : MHVCollectionInternal<MHVThingFilter *>
This is a public class - We can't append something with 'internal' in a public class. 'Internal' objects need to actually be internal and will should be added to a private directory so SDK consumers will have no access to it.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Types/MHVThingKey.h
> +@interface MHVThingKeyCollectionInternal : MHVCollectionInternal<MHVThingKey *> <XSerializable>
Here too. Internal cannot be in a public class.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Types/Private/MHVThingQueryResultInternal.h
> +@interface MHVThingQueryResultCollectionInternal : MHVCollectionInternal<MHVThingQueryResultInternal *>
This will need to be refactored too. Though this is an internal class we should delete MHVCollectionInternal.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Utilities/MHVValidator.h
> +MHVClientResult* MHVValidateCollection(MHVCollectionInternal *collection, MHVClientResultCode error);
MHVValidateCollection will need to be removed once MHVCollectionInternal is deleted.

2017-07-18 17:47 UTC, namalu commented on Example/healthvault-ios-sdk/MHVFeaturesConfiguration.m
> +//    config.masterApplicationId = [[NSUUID alloc] initWithUUIDString:@"7c81b435-f091-4444-9534-59eb53da66c9"];
Should this be reverted before merging?

2017-07-18 17:47 UTC, namalu commented on Example/healthvault-ios-sdk/ViewControllers/MHVTypeViewController.m
> +                               self.things = [self.things arrayByRemovingObject:selectedThing];
We shouldn't be using the SDK extensions in the sample app. I will be making most of the extensions private - also, this method should probably go away.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Extensions/MHVArrayExtensions.h
>  + (BOOL)isNilOrEmpty:(NSArray *)array;
I'm going to recommend we delete all methods in this file except for isNilOrEmpty. We need to clean up our extensions to include things that really make sense.

1. arrayByAddingObjectsFromArray:atStartingIndex: is used in the sample only, and should not be exposed publicly. 
2. arrayByRemovingObject: should just be done with a mutable array where needed.
3. hasElementsOfType: is not used anywhere.
4. addFromEnumerator: is not used anywhere.

2017-07-18 17:47 UTC, namalu commented on HealthVault/Classes/Models/Categories/NSArray+Utils.h
>  - (NSArray *)arrayByRemovingObject:(id)object;
This whole file needs to be cleaned up. Most of the methods are not used anywhere - They should be deleted. Also let's get rid of the convenience methods like arrayByRemovingObject: We should just do this with a mutable array where needed.

2017-07-18 18:17 UTC, miburf commented on HealthVault/Classes/Models/Categories/NSArray+Utils.h
>  - (NSArray *)arrayByRemovingObject:(id)object;
Removed all the unused methods & the one only used once

2017-07-18 18:20 UTC, miburf commented on HealthVault/Classes/Types/MHVThingFilter.h
> +@property (readwrite, nonatomic, strong)  NSArray<NSString *> *typeIDs;
wasn't needed, reverted the change

2017-07-18 18:25 UTC, miburf commented on Example/healthvault-ios-sdk/MHVFeaturesConfiguration.m
> +//    config.masterApplicationId = [[NSUUID alloc] initWithUUIDString:@"7c81b435-f091-4444-9534-59eb53da66c9"];
Yes, reverted

2017-07-18 18:25 UTC, miburf commented on HealthVault/Classes/Utilities/MHVValidator.h
> +MHVClientResult* MHVValidateCollection(MHVCollectionInternal *collection, MHVClientResultCode error);
Removed all the MHVCollection references

2017-07-18 20:28 UTC, miburf commented on HealthVault/Classes/Extensions/MHVArrayExtensions.h
>  + (BOOL)isNilOrEmpty:(NSArray *)array;
Moved isNileOrEmpty to NSArray+Utils and deleted the file ArrayExtensions file

2017-07-19 04:19 UTC, miburf commented on HealthVault/Classes/Types/MHVThingQuery.m
>      }
@namalu There's a bug here, it's not serializing the thing keys right.  You can reproduce by turning off caching, and then scrolling down on a page so it reloads the next batch.  Flying out tomorrow morning, and ran out of time to get it fixed. :(  Not serializing the right thing, so the query fails on HV.

2017-07-19 17:50 UTC, namalu approved these changes

2017-07-19 17:50 UTC, merged